---
version: '2'
services:
  zookeeper1-dc1:
    image: confluentinc/cp-zookeeper:7.3.3
    hostname: zookeeper1-dc1
    container_name: zookeeper1-dc1
    networks:
      - n1
    ports:
      - "2181:2181"
      - "9111:9111"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper1-dc1:2888:3888;zookeeper2-dc1:2888:3888;zookeeper3-dc1:2888:3888;zookeeper4-dc2:2888:3888;zookeeper5-dc2:2888:3888;zookeeper6-dc2:2888:3888
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
      ZOOKEEPER_GROUPS: 1:2:3;4:5:6
      KAFKA_JMX_PORT: 9111
      KAFKA_JMX_HOSTNAME: 127.0.0.1
    cap_add:
      - NET_ADMIN

  zookeeper2-dc1:
    image: confluentinc/cp-zookeeper:7.3.3
    hostname: zookeeper2-dc1
    container_name: zookeeper2-dc1
    networks:
      - n1
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper1-dc1:2888:3888;zookeeper2-dc1:2888:3888;zookeeper3-dc1:2888:3888;zookeeper4-dc2:2888:3888;zookeeper5-dc2:2888:3888;zookeeper6-dc2:2888:3888
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
      ZOOKEEPER_GROUPS: 1:2:3;4:5:6
    cap_add:
      - NET_ADMIN

  zookeeper3-dc1:
    image: confluentinc/cp-zookeeper:7.3.3
    hostname: zookeeper3-dc1
    container_name: zookeeper3-dc1
    networks:
      - n1
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper1-dc1:2888:3888;zookeeper2-dc1:2888:3888;zookeeper3-dc1:2888:3888;zookeeper4-dc2:2888:3888;zookeeper5-dc2:2888:3888;zookeeper6-dc2:2888:3888
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
      ZOOKEEPER_GROUPS: 1:2:3;4:5:6
    cap_add:
      - NET_ADMIN

  zookeeper4-dc2:
    image: confluentinc/cp-zookeeper:7.3.3
    hostname: zookeeper4-dc2
    container_name: zookeeper4-dc2
    networks:
      - n1
    ports:
      - "2184:2184"
    environment:
      ZOOKEEPER_SERVER_ID: 4
      ZOOKEEPER_CLIENT_PORT: 2184
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper1-dc1:2888:3888;zookeeper2-dc1:2888:3888;zookeeper3-dc1:2888:3888;zookeeper4-dc2:2888:3888;zookeeper5-dc2:2888:3888;zookeeper6-dc2:2888:3888
      #ZOOKEEPER_SERVERS: zookeeper4-dc2:2888:3888;zookeeper5-dc2:2888:3888;zookeeper6-dc2:2888:3888
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
      ZOOKEEPER_GROUPS: 1:2:3;4:5:6
    cap_add:
      - NET_ADMIN

  zookeeper5-dc2:
    image: confluentinc/cp-zookeeper:7.3.3
    hostname: zookeeper5-dc2
    container_name: zookeeper5-dc2
    networks:
      - n1
    ports:
      - "2185:2185"
    environment:
      ZOOKEEPER_SERVER_ID: 5
      ZOOKEEPER_CLIENT_PORT: 2185
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper1-dc1:2888:3888;zookeeper2-dc1:2888:3888;zookeeper3-dc1:2888:3888;zookeeper4-dc2:2888:3888;zookeeper5-dc2:2888:3888;zookeeper6-dc2:2888:3888
      #ZOOKEEPER_SERVERS: zookeeper4-dc2:2888:3888;zookeeper5-dc2:2888:3888;zookeeper6-dc2:2888:3888
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
      ZOOKEEPER_GROUPS: 1:2:3;4:5:6
    cap_add:
      - NET_ADMIN

  zookeeper6-dc2:
    image: confluentinc/cp-zookeeper:7.3.3
    hostname: zookeeper6-dc2
    container_name: zookeeper6-dc2
    networks:
      - n1
    ports:
      - "2186:2186"
    environment:
      ZOOKEEPER_SERVER_ID: 6
      ZOOKEEPER_CLIENT_PORT: 2186
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper1-dc1:2888:3888;zookeeper2-dc1:2888:3888;zookeeper3-dc1:2888:3888;zookeeper4-dc2:2888:3888;zookeeper5-dc2:2888:3888;zookeeper6-dc2:2888:3888
      #ZOOKEEPER_SERVERS: zookeeper4-dc2:2888:3888;zookeeper5-dc2:2888:3888;zookeeper6-dc2:2888:3888
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
      ZOOKEEPER_GROUPS: 1:2:3;4:5:6
    cap_add:
      - NET_ADMIN

  broker1-dc1:
    image: confluentinc/cp-server:7.3.3
    hostname: broker1-dc1
    container_name: broker1-dc1
    networks:
      - n1
    depends_on:
      - zookeeper1-dc1
      - zookeeper2-dc1
      - zookeeper3-dc1
      - zookeeper4-dc2
      - zookeeper5-dc2
      - zookeeper6-dc2
    cap_add:
      - NET_ADMIN  
    ports:
      - "9091:9091"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: 'dc1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1-dc1:29091,PLAINTEXT_HOST://localhost:9091
      KAFKA_REPLICA_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1-dc1:29091,broker2-dc1:29092,broker3-dc1:29093,broker4-dc2:29094,broker5-dc2:29095,broker6-dc2:29096
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 4
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 4
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: 127.0.0.1
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  broker2-dc1:
    image: confluentinc/cp-server:7.3.3
    hostname: broker2-dc1
    container_name: broker2-dc1
    networks:
      - n1
    depends_on:
      - zookeeper1-dc1
      - zookeeper2-dc1
      - zookeeper3-dc1
      - zookeeper4-dc2
      - zookeeper5-dc2
      - zookeeper6-dc2
    cap_add:
      - NET_ADMIN  
    ports:
      - "9092:9092"
      - "9102:9102"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_BROKER_RACK: 'dc1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2-dc1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_REPLICA_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1-dc1:29091,broker2-dc1:29092,broker3-dc1:29093,broker4-dc2:29094,broker5-dc2:29095,broker6-dc2:29096
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 4
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 4
      KAFKA_JMX_PORT: 9102
      KAFKA_JMX_HOSTNAME: 127.0.0.1
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  broker3-dc1:
    image: confluentinc/cp-server:7.3.3
    hostname: broker3-dc1
    container_name: broker3-dc1
    networks:
      - n1
    depends_on:
      - zookeeper1-dc1
      - zookeeper2-dc1
      - zookeeper3-dc1
      - zookeeper4-dc2
      - zookeeper5-dc2
      - zookeeper6-dc2
    cap_add:
      - NET_ADMIN  
    ports:
      - "9093:9093"
      - "9103:9103"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_BROKER_RACK: 'dc1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3-dc1:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_REPLICA_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1-dc1:29091,broker2-dc1:29092,broker3-dc1:29093,broker4-dc2:29094,broker5-dc2:29095,broker6-dc2:29096
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 4
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 4
      KAFKA_JMX_PORT: 9103
      KAFKA_JMX_HOSTNAME: 127.0.0.1
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  broker4-dc2:
    image: confluentinc/cp-server:7.3.3
    hostname: broker4-dc2
    container_name: broker4-dc2
    networks:
      - n1
    depends_on:
      - zookeeper1-dc1
      - zookeeper2-dc1
      - zookeeper3-dc1
      - zookeeper4-dc2
      - zookeeper5-dc2
      - zookeeper6-dc2
    cap_add:
      - NET_ADMIN  
    ports:
      - "9094:9094"
      - "9104:9104"
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_BROKER_RACK: 'dc2'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker4-dc2:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_REPLICA_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1-dc1:29091,broker2-dc1:29092,broker3-dc1:29093,broker4-dc2:29094,broker5-dc2:29095,broker6-dc2:29096
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 4
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 4
      KAFKA_JMX_PORT: 9104
      KAFKA_JMX_HOSTNAME: 127.0.0.1
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  broker5-dc2:
    image: confluentinc/cp-server:7.3.3
    hostname: broker5-dc2
    container_name: broker5-dc2
    networks:
      - n1
    depends_on:
      - zookeeper1-dc1
      - zookeeper2-dc1
      - zookeeper3-dc1
      - zookeeper4-dc2
      - zookeeper5-dc2
      - zookeeper6-dc2
    cap_add:
      - NET_ADMIN  
    ports:
      - "9095:9095"
      - "9105:9105"
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_BROKER_RACK: 'dc2'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker5-dc2:29095,PLAINTEXT_HOST://localhost:9095
      KAFKA_REPLICA_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1-dc1:29091,broker2-dc1:29092,broker3-dc1:29093,broker4-dc2:29094,broker5-dc2:29095,broker6-dc2:29096
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 4
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 4
      KAFKA_JMX_PORT: 9105
      KAFKA_JMX_HOSTNAME: 127.0.0.1
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  broker6-dc2:
    image: confluentinc/cp-server:7.3.3
    hostname: broker6-dc2
    container_name: broker6-dc2
    networks:
      - n1
    depends_on:
      - zookeeper1-dc1
      - zookeeper2-dc1
      - zookeeper3-dc1
      - zookeeper4-dc2
      - zookeeper5-dc2
      - zookeeper6-dc2
    cap_add:
      - NET_ADMIN  
    ports:
      - "9096:9096"
      - "9106:9106"
    environment:
      KAFKA_BROKER_ID: 6
      KAFKA_BROKER_RACK: 'dc2'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker6-dc2:29096,PLAINTEXT_HOST://localhost:9096
      KAFKA_REPLICA_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1-dc1:29091,broker2-dc1:29092,broker3-dc1:29093,broker4-dc2:29094,broker5-dc2:29095,broker6-dc2:29096
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 4
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 4
      KAFKA_JMX_PORT: 9106
      KAFKA_JMX_HOSTNAME: 127.0.0.1
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.3
    hostname: control-center
    container_name: control-center
    networks:
      - n1
    depends_on:
      - zookeeper1-dc1
      - zookeeper2-dc1
      - zookeeper3-dc1
      - zookeeper4-dc2
      - zookeeper5-dc2
      - zookeeper6-dc2
      - broker1-dc1
      - broker2-dc1
      - broker3-dc1
      - broker4-dc2
      - broker5-dc2
      - broker6-dc2
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker1-dc1:29091,broker2-dc1:29092,broker3-dc1:29093,broker4-dc2:29094,broker5-dc2:29095,broker6-dc2:29096'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper1-dc1:2181,zookeeper2-dc1:2182,zookeeper3-dc1:2183,zookeeper4-dc2:2184,zookeeper5-dc2:2185,zookeeper6-dc2:2186'
      CONTROL_CENTER_REPLICATION_FACTOR: 4
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 6
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 6
      CONFLUENT_METRICS_TOPIC_REPLICATION: 3
      PORT: 9021

networks:
  n1:
      